---
# tasks file for ansible-role-fairdom-seek

- include: prereq.yml

- include: mysql_install.yml

- include: seek.yml
  environment:
    RAILS_ENV: production
  become_user: www-data
  become: true

- include: virtuoso.yml
