---
#https://gist.github.com/ihassin/8106956

- name: Install MySQL
  apt:
    name: "{{ packages }}" 
    state: present
  vars:
    packages:
    - mysql-server
    - python-pymysql

- name: Write root login credentials
  copy:
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
    content: |
        [client]
        user=root
        password={{ mysql_root_password }}
        socket=/var/run/mysqld/mysqld.sock

- name: Start the MySQL service
  service:
    name: mysql
    state: started
    enabled: true

- name: Remove the test database
  mysql_db:
    name: test
    state: absent

- name: Create seek user for mysql
  mysql_user:
    user: "{{ mysql_seek_user }}"
    host: "%"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"

- name: Ensure anonymous users are not in the database
  mysql_user:
    user: ''
    host: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy .my.cnf file with root password credentials
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    mode: 0600

- name: Update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
