---
- name: Clone seek
  git:
    repo: 'https://github.com/seek4science/seek.git'
    dest: '/srv/seek'
    version: 'v1.7.1'

# Setting up Ruby and RubyGems with RVM

#- shell: '\curl -L https://get.rvm.io | bash'


