---
- name: Create seek directory
  file:
    path: '/srv/seek'
    state: directory
    owner: 'www-data'
    group: 'www-data'
  become_user: root
  become_method: sudo

- name: Clone seek
  git:
    repo: 'https://github.com/seek4science/seek.git'
    dest: '/srv/seek'
    version: 'v1.7.1'
#______________________________________
# Setting up Ruby and RubyGems with RVM

- name: Install rvm
  shell: '\curl -L https://get.rvm.io | bash'
  become_user: root
  become_method: sudo

- name: Add www-data to rvm group 
  user:
    name: www-data
    shell: /bin/bash
    groups: rvm
    append: yes

- name: Install Ruby
  shell: 'source /etc/profile.d/rvm.sh && /usr/local/rvm/bin/rvm install $(cat .ruby-version)'
  args:
    chdir: /srv/seek
    executable: /bin/bash

#______________________________________
# Installing Gems

- name: Install bundler
  shell: 'source /etc/profile.d/rvm.sh && gem install bundler'
  args:
    chdir: /srv/seek
    executable: /bin/bash

- name: Install ruby gems SEEK needs
  shell: 'source /etc/profile.d/rvm.sh && bundle install'
  args:
    chdir: /srv/seek
    executable: /bin/bash


#______________________________________
# Setting up the Database

- name: Create seek user for mysql
  mysql_user:
    user: "{{ mysql_seek_user }}"
    host: "%"
    password: "{{ mysql_seek_password }}"
    priv: "*.*:ALL,GRANT"

- name: Setup db configuration file
  template:
    src: database.yml.j2
    dest: /srv/seek/config/database.yml
    remote_src: yes

- name: Create the database for SEEK and seed it with the default data
  shell: 'source /etc/profile.d/rvm.sh && bundle exec rake db:setup > /tmp/seek_db_craete.log'
  args:
    chdir: /srv/seek
    executable: /bin/bash

#______________________________________
# Compiling Assets

- name: Create the database for SEEK and seed it with the default data
  shell: 'source /etc/profile.d/rvm.sh && bundle exec rake assets:precompile'
  args:
    chdir: /srv/seek
    executable: /bin/bash
