---
- name: Install virtuoso
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - virtuoso-opensource

- name: Enable virtuoso init file
  replace:
    path: /etc/default/virtuoso-opensource-6.1
    regexp: "RUN=no"
    replace: "RUN=yes"

- name: Start virtuoso
  service:
    name: virtuoso-opensource-6.1
    state: started
    enabled: yes

- name: Change virtuoso dba password
  shell: "echo \"user_set_password('dba', '{{ virtuoso_dba_password }}');\" | isql-vt 1111 dba {{ virtuoso_dba_password_default }}"
  args:
    creates: '/tmp/virtuoso_dba_password_change.log'
  register: virtuoso_password_change_register

- shell: "echo '{{ virtuoso_password_change_register.stdout }}' > /tmp/virtuoso_dba_password_change.log"
  args:
    creates: '/tmp/virtuoso_dba_password_change.log'

# Soruce from:
# https://www.apt-browse.org/browse/ubuntu/trusty/universe/i386/virtuoso-opensource-6.1/6.1.6+repack-0ubuntu3/debian/postinst
- name: Change virtuoso dav password
  shell: "echo \"UPDATE SYS_USERS SET U_PASSWORD='{{ virtuoso_dav_password }}' WHERE U_NAME='dav';\" | isql-vt 1111 dba {{ virtuoso_dba_password }}"
  args:
    creates: '/tmp/virtuoso_dav_password_change.log'
  register: virtuoso_dav_password_change_register

- shell: "echo '{{ virtuoso_dav_password_change_register.stdout }}' > /tmp/virtuoso_dav_password_change.log"
  args:
    creates: '/tmp/virtuoso_dav_password_change.log'

- name: "Set additional privileges for deleting triples (1)"
  shell: "echo 'grant execute on SPARQL_DELETE_DICT_CONTENT to \"SPARQL\";' | isql-vt 1111  dba {{ virtuoso_dba_password }}"

- name: "set additional privileges for deleting triples (2)"
  shell: "echo 'grant execute on SPARQL_DELETE_DICT_CONTENT to SPARQL_UPDATE;' | isql-vt 1111 dba {{ virtuoso_dba_password }}"
